# Generated by Django 4.0.3 on 2022-03-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a test description for my django e-commerce project. select an option, please provide a one-off defaoult now... will be set on all existing rows witha null value for this column, quit and manually define a default value in models.py'),
            preserve_default=False,
        ),
    ]
