# Generated by Django 4.0.3 on 2022-04-01 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
